### ISSUE TITLE
New option to skip a camera 

### ISSUE THREAD

**Issue by anddag** [DavidVentura/cam-reverse#22]
In my network there are 3 cameras that use the ILINKP2P protocol. One of them is very old (detected but the video dont is shown) and I would like to exclude it from the search. Could you implement an option  to esclude some IP o Cameras from discovery and handshake?

**Comment by DavidVentura** [comment]
The serial number is only known after handshake, so it'd be hard to ignore devices before then. Ignoring based on IP address would be easier

**Comment by anddag** [comment]
Ok for ip Based :-)

Il giorno dom 5 mag 2024 alle ore 16:35 David Ventura <
***@***.***> ha scritto:

**Comment by DavidVentura** [comment]
It's now pushed, with d5d4161dd8892cdecd158201f65615685065f5a5

You will need to provide a settings file and `--config_file` for the webserver.

You can provide jsut the blacklist key, eg :
```yaml
blacklisted_ips:
  - 192.168.1.81
```

check [the config sample file](https://github.com/DavidVentura/cam-reverse/blob/master/config.example.yml) for all settings
