### ISSUE TITLE
Single image option

### ISSUE THREAD

**Issue by uwe-schwarz** [DavidVentura/cam-reverse#32]
Thanks for the project, I got everything working great so far.

Would it be possible to get a single image from a single camera? I only need one image every 15 minutes and no stream.

This would be perfect for me:
`node bin.cjs frame --discovery_ip xxx --out frame.jpg`

**Comment by DavidVentura** [comment]
Just added it, try it out and let me know -- you can get v0.4 here: https://github.com/DavidVentura/cam-reverse/releases/tag/v0.4 or just re-build from master

**Comment by uwe-schwarz** [comment]
Wow, that's just stunning and fast :) Works as expected, thank you!
