### ISSUE TITLE
Question: Compatibility with A9 Cameras in Frigate or go2rtc

### ISSUE THREAD

**Issue by juancarlosromerogarcia** [DavidVentura/cam-reverse#45]
Hello,

I've successfully set up cam-reverse and can view the camera feed in browsers and through Home Assistant using the MJPEG IP Camera integration. However, I'm unable to get it working directly with Frigate or through go2rtc. Specifically, I'm wondering if it's possible to use A9 type cameras with this software in Frigate or go2rtc.

Also, I'd like to express my gratitude to the developer for their effort and dedication to this project.

Thank you.

**Comment by DavidVentura** [comment]
Seems like `go2rtc` has an [interesting](https://github.com/AlexxIT/go2rtc/blob/ef7d8987473a6fb0bcb4ac5b9499eb90810c1566/pkg/mpjpeg/multipart.go#L13) implementation for parsing multipart streams, demanding an extra newline before each payload.

I've just pushed a new commit which works with `go2rtc` (related to #40, @b2un0), and released v0.5 with the change
