### ISSUE TITLE
--discovery_ip not used in pair

### ISSUE THREAD

**Issue by adlerweb** [DavidVentura/cam-reverse#47]
the param `--discovery_ip 192.168.1.1`  is not working with command 'pair'. Changing the corresponding parameters in bin.cjs works.

(also reported by @rundekugel in https://github.com/DavidVentura/cam-reverse/issues/44#issuecomment-2425171020_)

**Comment by DavidVentura** [comment]
can you try master now?

**Comment by adlerweb** [comment]
Yepp, now it works as expected
